remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
title: "AI JAVA GEEK"
subtitle: "Welcome to AI Java space"
name: "AI JAVA GEEK"
include:
  - _pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
